/*
 * This file is generated by jOOQ.
 */
package com.example.backend.db.generatedJooqCode;


import com.example.backend.db.generatedJooqCode.tables.JBooks;

import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Integer> IDENTITY_BOOKS = Identities0.IDENTITY_BOOKS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> KEY_BOOKS_PRIMARY = UniqueKeys0.KEY_BOOKS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<Record, Integer> IDENTITY_BOOKS = Internal.createIdentity(JBooks.BOOKS, JBooks.BOOKS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> KEY_BOOKS_PRIMARY = Internal.createUniqueKey(JBooks.BOOKS, "KEY_books_PRIMARY", new TableField[] { JBooks.BOOKS.ID }, true);
    }
}
