/*
 * This file is generated by jOOQ.
 */
package com.example.backend.db.generatedJooqCode;


import com.example.backend.db.generatedJooqCode.tables.JBooks;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Table which is for managing books
     */
    public static final JBooks BOOKS = JBooks.BOOKS;
}
