spring:
  datasource:
    url: "jdbc:mysql://\
          ${DATASOURCE_DATABASE_HOST:127.0.0.1}:\
          ${DATASOURCE_DATABASE_PORT:3306}/\
          ${DATASOURCE_DATABASE_NAME:nuxt_apollo_spring_graphql_authnz_sample_dev}\
          ${DATASOURCE_DATABASE_QUERY:?characterEncoding=UTF8&connectionCollation=utf8mb4_bin&useSSL=false}"
    username: ${DATASOURCE_DATABASE_USERNAME:root}
    password: ${DATASOURCE_DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariDataSource is default type, but it's written explicitly.
    type: com.zaxxer.hikari.HikariDataSource
    # HikariCP
    # @link https://github.com/brettwooldridge/HikariCP#frequently-used
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 10
    flyway:
      user: ${DATASOURCE_DATABASE_MIGRATION_USERNAME:root}
      password: ${DATASOURCE_DATABASE_PASSWORD:}

# Properties to use in application source files.
application:
  url:
    frontend-application-base-url: ${APPLICATION_URL_FRONTEND_APPLICATION_BASE_URL:http://localhost:3000}
    backend-file-application-base-url: ${APPLICATION_URL_BACKEND_FILE_APPLICATION_BASE_URL:}
  # Property to use in Spring Security.
  security:
    # カンマ繋ぎで複数指定することができるが、現時点で複数指定しているのは開発環境のみ。
    # localhostの各portはそれぞれ以下のフロントエンドAPPのもの。
    #
    # localhost:7000 : frontend-admin
    # localhost:8000 : frontend-main
    allowed-frontend-domain: ${APPLICATION_SECURITY_ALLOWED_FRONTEND_DOMAIN:http://localhost:7000,http://localhost:3000}
